/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables;


import br.ufsc.INE5608.homechef.Homechef;
import br.ufsc.INE5608.homechef.Keys;
import br.ufsc.INE5608.homechef.tables.records.EnDificuldadeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnDificuldade extends TableImpl<EnDificuldadeRecord> {

    private static final long serialVersionUID = 607786376;

    /**
     * The reference instance of <code>homechef.en_dificuldade</code>
     */
    public static final EnDificuldade EN_DIFICULDADE = new EnDificuldade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EnDificuldadeRecord> getRecordType() {
        return EnDificuldadeRecord.class;
    }

    /**
     * The column <code>homechef.en_dificuldade.id_dificuldade</code>.
     */
    public final TableField<EnDificuldadeRecord, Integer> ID_DIFICULDADE = createField("id_dificuldade", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('homechef.en_dificuldade_id_dificuldade_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>homechef.en_dificuldade.nome</code>.
     */
    public final TableField<EnDificuldadeRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>homechef.en_dificuldade</code> table reference
     */
    public EnDificuldade() {
        this("en_dificuldade", null);
    }

    /**
     * Create an aliased <code>homechef.en_dificuldade</code> table reference
     */
    public EnDificuldade(String alias) {
        this(alias, EN_DIFICULDADE);
    }

    private EnDificuldade(String alias, Table<EnDificuldadeRecord> aliased) {
        this(alias, aliased, null);
    }

    private EnDificuldade(String alias, Table<EnDificuldadeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Homechef.HOMECHEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EnDificuldadeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EN_DIFICULDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EnDificuldadeRecord> getPrimaryKey() {
        return Keys.EN_DIFICULDADE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EnDificuldadeRecord>> getKeys() {
        return Arrays.<UniqueKey<EnDificuldadeRecord>>asList(Keys.EN_DIFICULDADE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnDificuldade as(String alias) {
        return new EnDificuldade(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnDificuldade rename(String name) {
        return new EnDificuldade(name, null);
    }
}
