/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables;


import br.ufsc.INE5608.homechef.Homechef;
import br.ufsc.INE5608.homechef.Keys;
import br.ufsc.INE5608.homechef.tables.records.EnIngredienteRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnIngrediente extends TableImpl<EnIngredienteRecord> {

    private static final long serialVersionUID = -1252681332;

    /**
     * The reference instance of <code>homechef.en_ingrediente</code>
     */
    public static final EnIngrediente EN_INGREDIENTE = new EnIngrediente();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EnIngredienteRecord> getRecordType() {
        return EnIngredienteRecord.class;
    }

    /**
     * The column <code>homechef.en_ingrediente.id_ingrediente</code>.
     */
    public final TableField<EnIngredienteRecord, Integer> ID_INGREDIENTE = createField("id_ingrediente", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('homechef.en_ingrediente_id_ingrediente_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>homechef.en_ingrediente.nome</code>.
     */
    public final TableField<EnIngredienteRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>homechef.en_ingrediente.preco</code>.
     */
    public final TableField<EnIngredienteRecord, BigDecimal> PRECO = createField("preco", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>homechef.en_ingrediente.id_unidade</code>.
     */
    public final TableField<EnIngredienteRecord, Integer> ID_UNIDADE = createField("id_unidade", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>homechef.en_ingrediente</code> table reference
     */
    public EnIngrediente() {
        this("en_ingrediente", null);
    }

    /**
     * Create an aliased <code>homechef.en_ingrediente</code> table reference
     */
    public EnIngrediente(String alias) {
        this(alias, EN_INGREDIENTE);
    }

    private EnIngrediente(String alias, Table<EnIngredienteRecord> aliased) {
        this(alias, aliased, null);
    }

    private EnIngrediente(String alias, Table<EnIngredienteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Homechef.HOMECHEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EnIngredienteRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EN_INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EnIngredienteRecord> getPrimaryKey() {
        return Keys.EN_INGREDIENTE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EnIngredienteRecord>> getKeys() {
        return Arrays.<UniqueKey<EnIngredienteRecord>>asList(Keys.EN_INGREDIENTE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EnIngredienteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EnIngredienteRecord, ?>>asList(Keys.EN_INGREDIENTE__EN_INGREDIENTE_EN_UNIDADE_ID_UNIDADE_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnIngrediente as(String alias) {
        return new EnIngrediente(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnIngrediente rename(String name) {
        return new EnIngrediente(name, null);
    }
}
