/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables;


import br.ufsc.INE5608.homechef.Homechef;
import br.ufsc.INE5608.homechef.Keys;
import br.ufsc.INE5608.homechef.tables.records.EnReceitaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnReceita extends TableImpl<EnReceitaRecord> {

    private static final long serialVersionUID = -1682421872;

    /**
     * The reference instance of <code>homechef.en_receita</code>
     */
    public static final EnReceita EN_RECEITA = new EnReceita();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EnReceitaRecord> getRecordType() {
        return EnReceitaRecord.class;
    }

    /**
     * The column <code>homechef.en_receita.id_receita</code>.
     */
    public final TableField<EnReceitaRecord, Integer> ID_RECEITA = createField("id_receita", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('homechef.en_receita_id_receita_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>homechef.en_receita.id_dificuldade</code>.
     */
    public final TableField<EnReceitaRecord, Integer> ID_DIFICULDADE = createField("id_dificuldade", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homechef.en_receita.modo_preparo</code>.
     */
    public final TableField<EnReceitaRecord, String> MODO_PREPARO = createField("modo_preparo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>homechef.en_receita.nome</code>.
     */
    public final TableField<EnReceitaRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>homechef.en_receita.tempo</code>.
     */
    public final TableField<EnReceitaRecord, Integer> TEMPO = createField("tempo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>homechef.en_receita</code> table reference
     */
    public EnReceita() {
        this("en_receita", null);
    }

    /**
     * Create an aliased <code>homechef.en_receita</code> table reference
     */
    public EnReceita(String alias) {
        this(alias, EN_RECEITA);
    }

    private EnReceita(String alias, Table<EnReceitaRecord> aliased) {
        this(alias, aliased, null);
    }

    private EnReceita(String alias, Table<EnReceitaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Homechef.HOMECHEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EnReceitaRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EN_RECEITA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EnReceitaRecord> getPrimaryKey() {
        return Keys.EN_RECEITA_ID_RECEITA_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EnReceitaRecord>> getKeys() {
        return Arrays.<UniqueKey<EnReceitaRecord>>asList(Keys.EN_RECEITA_ID_RECEITA_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EnReceitaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EnReceitaRecord, ?>>asList(Keys.EN_RECEITA__EN_RECEITA_EN_DIFICULDADE_ID_DIFICULDADE_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnReceita as(String alias) {
        return new EnReceita(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnReceita rename(String name) {
        return new EnReceita(name, null);
    }
}
