/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables;


import br.ufsc.INE5608.homechef.Homechef;
import br.ufsc.INE5608.homechef.Keys;
import br.ufsc.INE5608.homechef.tables.records.ReUnidadeUnidadeRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReUnidadeUnidade extends TableImpl<ReUnidadeUnidadeRecord> {

    private static final long serialVersionUID = 1604114363;

    /**
     * The reference instance of <code>homechef.re_unidade_unidade</code>
     */
    public static final ReUnidadeUnidade RE_UNIDADE_UNIDADE = new ReUnidadeUnidade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReUnidadeUnidadeRecord> getRecordType() {
        return ReUnidadeUnidadeRecord.class;
    }

    /**
     * The column <code>homechef.re_unidade_unidade.id_unidade_origem</code>.
     */
    public final TableField<ReUnidadeUnidadeRecord, Integer> ID_UNIDADE_ORIGEM = createField("id_unidade_origem", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homechef.re_unidade_unidade.id_unidade_destino</code>.
     */
    public final TableField<ReUnidadeUnidadeRecord, Integer> ID_UNIDADE_DESTINO = createField("id_unidade_destino", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homechef.re_unidade_unidade.multiplicador</code>.
     */
    public final TableField<ReUnidadeUnidadeRecord, BigDecimal> MULTIPLICADOR = createField("multiplicador", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * Create a <code>homechef.re_unidade_unidade</code> table reference
     */
    public ReUnidadeUnidade() {
        this("re_unidade_unidade", null);
    }

    /**
     * Create an aliased <code>homechef.re_unidade_unidade</code> table reference
     */
    public ReUnidadeUnidade(String alias) {
        this(alias, RE_UNIDADE_UNIDADE);
    }

    private ReUnidadeUnidade(String alias, Table<ReUnidadeUnidadeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReUnidadeUnidade(String alias, Table<ReUnidadeUnidadeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Homechef.HOMECHEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReUnidadeUnidadeRecord> getPrimaryKey() {
        return Keys.RE_UNIDADE_UNIDADE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReUnidadeUnidadeRecord>> getKeys() {
        return Arrays.<UniqueKey<ReUnidadeUnidadeRecord>>asList(Keys.RE_UNIDADE_UNIDADE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReUnidadeUnidadeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReUnidadeUnidadeRecord, ?>>asList(Keys.RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_FK, Keys.RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_DESTINO_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReUnidadeUnidade as(String alias) {
        return new ReUnidadeUnidade(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReUnidadeUnidade rename(String name) {
        return new ReUnidadeUnidade(name, null);
    }
}
