/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef;


import br.ufsc.INE5608.homechef.tables.EnDificuldade;
import br.ufsc.INE5608.homechef.tables.EnIngrediente;
import br.ufsc.INE5608.homechef.tables.EnItemEstoque;
import br.ufsc.INE5608.homechef.tables.EnReceita;
import br.ufsc.INE5608.homechef.tables.EnUnidade;
import br.ufsc.INE5608.homechef.tables.ReIngredienteReceita;
import br.ufsc.INE5608.homechef.tables.ReUnidadeUnidade;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Homechef extends SchemaImpl {

    private static final long serialVersionUID = 1642051585;

    /**
     * The reference instance of <code>homechef</code>
     */
    public static final Homechef HOMECHEF = new Homechef();

    /**
     * The table <code>homechef.en_dificuldade</code>.
     */
    public final EnDificuldade EN_DIFICULDADE = br.ufsc.INE5608.homechef.tables.EnDificuldade.EN_DIFICULDADE;

    /**
     * The table <code>homechef.en_ingrediente</code>.
     */
    public final EnIngrediente EN_INGREDIENTE = br.ufsc.INE5608.homechef.tables.EnIngrediente.EN_INGREDIENTE;

    /**
     * The table <code>homechef.en_item_estoque</code>.
     */
    public final EnItemEstoque EN_ITEM_ESTOQUE = br.ufsc.INE5608.homechef.tables.EnItemEstoque.EN_ITEM_ESTOQUE;

    /**
     * The table <code>homechef.en_receita</code>.
     */
    public final EnReceita EN_RECEITA = br.ufsc.INE5608.homechef.tables.EnReceita.EN_RECEITA;

    /**
     * The table <code>homechef.en_unidade</code>.
     */
    public final EnUnidade EN_UNIDADE = br.ufsc.INE5608.homechef.tables.EnUnidade.EN_UNIDADE;

    /**
     * The table <code>homechef.re_ingrediente_receita</code>.
     */
    public final ReIngredienteReceita RE_INGREDIENTE_RECEITA = br.ufsc.INE5608.homechef.tables.ReIngredienteReceita.RE_INGREDIENTE_RECEITA;

    /**
     * The table <code>homechef.re_unidade_unidade</code>.
     */
    public final ReUnidadeUnidade RE_UNIDADE_UNIDADE = br.ufsc.INE5608.homechef.tables.ReUnidadeUnidade.RE_UNIDADE_UNIDADE;

    /**
     * No further instances allowed
     */
    private Homechef() {
        super("homechef", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.EN_DIFICULDADE_ID_DIFICULDADE_SEQ,
            Sequences.EN_INGREDIENTE_ID_INGREDIENTE_SEQ,
            Sequences.EN_INGREDIENTE_RECEITA_ID_INGREDIENTE_RECEITA_SEQ,
            Sequences.EN_ITEM_ESTOQUE_ID_ITEM_ESTOQUE_SEQ,
            Sequences.EN_RECEITA_ID_RECEITA_SEQ,
            Sequences.EN_UNIDADE_ID_UNIDADE_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            EnDificuldade.EN_DIFICULDADE,
            EnIngrediente.EN_INGREDIENTE,
            EnItemEstoque.EN_ITEM_ESTOQUE,
            EnReceita.EN_RECEITA,
            EnUnidade.EN_UNIDADE,
            ReIngredienteReceita.RE_INGREDIENTE_RECEITA,
            ReUnidadeUnidade.RE_UNIDADE_UNIDADE);
    }
}
