/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef;


import br.ufsc.INE5608.homechef.tables.EnDificuldade;
import br.ufsc.INE5608.homechef.tables.EnIngrediente;
import br.ufsc.INE5608.homechef.tables.EnItemEstoque;
import br.ufsc.INE5608.homechef.tables.EnReceita;
import br.ufsc.INE5608.homechef.tables.EnUnidade;
import br.ufsc.INE5608.homechef.tables.ReIngredienteReceita;
import br.ufsc.INE5608.homechef.tables.ReUnidadeUnidade;
import br.ufsc.INE5608.homechef.tables.records.EnDificuldadeRecord;
import br.ufsc.INE5608.homechef.tables.records.EnIngredienteRecord;
import br.ufsc.INE5608.homechef.tables.records.EnItemEstoqueRecord;
import br.ufsc.INE5608.homechef.tables.records.EnReceitaRecord;
import br.ufsc.INE5608.homechef.tables.records.EnUnidadeRecord;
import br.ufsc.INE5608.homechef.tables.records.ReIngredienteReceitaRecord;
import br.ufsc.INE5608.homechef.tables.records.ReUnidadeUnidadeRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>homechef</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EnDificuldadeRecord, Integer> IDENTITY_EN_DIFICULDADE = Identities0.IDENTITY_EN_DIFICULDADE;
    public static final Identity<EnIngredienteRecord, Integer> IDENTITY_EN_INGREDIENTE = Identities0.IDENTITY_EN_INGREDIENTE;
    public static final Identity<EnItemEstoqueRecord, Integer> IDENTITY_EN_ITEM_ESTOQUE = Identities0.IDENTITY_EN_ITEM_ESTOQUE;
    public static final Identity<EnReceitaRecord, Integer> IDENTITY_EN_RECEITA = Identities0.IDENTITY_EN_RECEITA;
    public static final Identity<EnUnidadeRecord, Integer> IDENTITY_EN_UNIDADE = Identities0.IDENTITY_EN_UNIDADE;
    public static final Identity<ReIngredienteReceitaRecord, Integer> IDENTITY_RE_INGREDIENTE_RECEITA = Identities0.IDENTITY_RE_INGREDIENTE_RECEITA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EnDificuldadeRecord> EN_DIFICULDADE_PKEY = UniqueKeys0.EN_DIFICULDADE_PKEY;
    public static final UniqueKey<EnIngredienteRecord> EN_INGREDIENTE_PKEY = UniqueKeys0.EN_INGREDIENTE_PKEY;
    public static final UniqueKey<EnItemEstoqueRecord> EN_ITEM_ESTOQUE_ID_ITEM_ESTOQUE_PK = UniqueKeys0.EN_ITEM_ESTOQUE_ID_ITEM_ESTOQUE_PK;
    public static final UniqueKey<EnReceitaRecord> EN_RECEITA_ID_RECEITA_PK = UniqueKeys0.EN_RECEITA_ID_RECEITA_PK;
    public static final UniqueKey<EnUnidadeRecord> EN_UNIDADE_PKEY = UniqueKeys0.EN_UNIDADE_PKEY;
    public static final UniqueKey<ReIngredienteReceitaRecord> EN_INGREDIENTE_RECEITA_PKEY = UniqueKeys0.EN_INGREDIENTE_RECEITA_PKEY;
    public static final UniqueKey<ReUnidadeUnidadeRecord> RE_UNIDADE_UNIDADE_PKEY = UniqueKeys0.RE_UNIDADE_UNIDADE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EnIngredienteRecord, EnUnidadeRecord> EN_INGREDIENTE__EN_INGREDIENTE_EN_UNIDADE_ID_UNIDADE_FK = ForeignKeys0.EN_INGREDIENTE__EN_INGREDIENTE_EN_UNIDADE_ID_UNIDADE_FK;
    public static final ForeignKey<EnItemEstoqueRecord, EnIngredienteRecord> EN_ITEM_ESTOQUE__EN_ITEM_ESTOQUE_EN_INGREDIENTE_ID_INGREDIENTE_FK = ForeignKeys0.EN_ITEM_ESTOQUE__EN_ITEM_ESTOQUE_EN_INGREDIENTE_ID_INGREDIENTE_FK;
    public static final ForeignKey<EnItemEstoqueRecord, EnUnidadeRecord> EN_ITEM_ESTOQUE__EN_ITEM_ESTOQUE_EN_UNIDADE_ID_UNIDADE_FK = ForeignKeys0.EN_ITEM_ESTOQUE__EN_ITEM_ESTOQUE_EN_UNIDADE_ID_UNIDADE_FK;
    public static final ForeignKey<EnReceitaRecord, EnDificuldadeRecord> EN_RECEITA__EN_RECEITA_EN_DIFICULDADE_ID_DIFICULDADE_FK = ForeignKeys0.EN_RECEITA__EN_RECEITA_EN_DIFICULDADE_ID_DIFICULDADE_FK;
    public static final ForeignKey<ReIngredienteReceitaRecord, EnIngredienteRecord> RE_INGREDIENTE_RECEITA__EN_INGREDIENTE_RECEITA_EN_INGREDIENTE_ID_INGREDIENTE_FK = ForeignKeys0.RE_INGREDIENTE_RECEITA__EN_INGREDIENTE_RECEITA_EN_INGREDIENTE_ID_INGREDIENTE_FK;
    public static final ForeignKey<ReUnidadeUnidadeRecord, EnUnidadeRecord> RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_FK = ForeignKeys0.RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_FK;
    public static final ForeignKey<ReUnidadeUnidadeRecord, EnUnidadeRecord> RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_DESTINO_FK = ForeignKeys0.RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_DESTINO_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<EnDificuldadeRecord, Integer> IDENTITY_EN_DIFICULDADE = createIdentity(EnDificuldade.EN_DIFICULDADE, EnDificuldade.EN_DIFICULDADE.ID_DIFICULDADE);
        public static Identity<EnIngredienteRecord, Integer> IDENTITY_EN_INGREDIENTE = createIdentity(EnIngrediente.EN_INGREDIENTE, EnIngrediente.EN_INGREDIENTE.ID_INGREDIENTE);
        public static Identity<EnItemEstoqueRecord, Integer> IDENTITY_EN_ITEM_ESTOQUE = createIdentity(EnItemEstoque.EN_ITEM_ESTOQUE, EnItemEstoque.EN_ITEM_ESTOQUE.ID_ITEM_ESTOQUE);
        public static Identity<EnReceitaRecord, Integer> IDENTITY_EN_RECEITA = createIdentity(EnReceita.EN_RECEITA, EnReceita.EN_RECEITA.ID_RECEITA);
        public static Identity<EnUnidadeRecord, Integer> IDENTITY_EN_UNIDADE = createIdentity(EnUnidade.EN_UNIDADE, EnUnidade.EN_UNIDADE.ID_UNIDADE);
        public static Identity<ReIngredienteReceitaRecord, Integer> IDENTITY_RE_INGREDIENTE_RECEITA = createIdentity(ReIngredienteReceita.RE_INGREDIENTE_RECEITA, ReIngredienteReceita.RE_INGREDIENTE_RECEITA.ID_INGREDIENTE_RECEITA);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<EnDificuldadeRecord> EN_DIFICULDADE_PKEY = createUniqueKey(EnDificuldade.EN_DIFICULDADE, "en_dificuldade_pkey", EnDificuldade.EN_DIFICULDADE.ID_DIFICULDADE);
        public static final UniqueKey<EnIngredienteRecord> EN_INGREDIENTE_PKEY = createUniqueKey(EnIngrediente.EN_INGREDIENTE, "en_ingrediente_pkey", EnIngrediente.EN_INGREDIENTE.ID_INGREDIENTE);
        public static final UniqueKey<EnItemEstoqueRecord> EN_ITEM_ESTOQUE_ID_ITEM_ESTOQUE_PK = createUniqueKey(EnItemEstoque.EN_ITEM_ESTOQUE, "en_item_estoque_id_item_estoque_pk", EnItemEstoque.EN_ITEM_ESTOQUE.ID_ITEM_ESTOQUE);
        public static final UniqueKey<EnReceitaRecord> EN_RECEITA_ID_RECEITA_PK = createUniqueKey(EnReceita.EN_RECEITA, "en_receita_id_receita_pk", EnReceita.EN_RECEITA.ID_RECEITA);
        public static final UniqueKey<EnUnidadeRecord> EN_UNIDADE_PKEY = createUniqueKey(EnUnidade.EN_UNIDADE, "en_unidade_pkey", EnUnidade.EN_UNIDADE.ID_UNIDADE);
        public static final UniqueKey<ReIngredienteReceitaRecord> EN_INGREDIENTE_RECEITA_PKEY = createUniqueKey(ReIngredienteReceita.RE_INGREDIENTE_RECEITA, "en_ingrediente_receita_pkey", ReIngredienteReceita.RE_INGREDIENTE_RECEITA.ID_INGREDIENTE_RECEITA);
        public static final UniqueKey<ReUnidadeUnidadeRecord> RE_UNIDADE_UNIDADE_PKEY = createUniqueKey(ReUnidadeUnidade.RE_UNIDADE_UNIDADE, "re_unidade_unidade_pkey", ReUnidadeUnidade.RE_UNIDADE_UNIDADE.ID_UNIDADE_ORIGEM, ReUnidadeUnidade.RE_UNIDADE_UNIDADE.ID_UNIDADE_DESTINO);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<EnIngredienteRecord, EnUnidadeRecord> EN_INGREDIENTE__EN_INGREDIENTE_EN_UNIDADE_ID_UNIDADE_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_UNIDADE_PKEY, EnIngrediente.EN_INGREDIENTE, "en_ingrediente__en_ingrediente_en_unidade_id_unidade_fk", EnIngrediente.EN_INGREDIENTE.ID_UNIDADE);
        public static final ForeignKey<EnItemEstoqueRecord, EnIngredienteRecord> EN_ITEM_ESTOQUE__EN_ITEM_ESTOQUE_EN_INGREDIENTE_ID_INGREDIENTE_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_INGREDIENTE_PKEY, EnItemEstoque.EN_ITEM_ESTOQUE, "en_item_estoque__en_item_estoque_en_ingrediente_id_ingrediente_fk", EnItemEstoque.EN_ITEM_ESTOQUE.ID_INGREDIENTE);
        public static final ForeignKey<EnItemEstoqueRecord, EnUnidadeRecord> EN_ITEM_ESTOQUE__EN_ITEM_ESTOQUE_EN_UNIDADE_ID_UNIDADE_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_UNIDADE_PKEY, EnItemEstoque.EN_ITEM_ESTOQUE, "en_item_estoque__en_item_estoque_en_unidade_id_unidade_fk", EnItemEstoque.EN_ITEM_ESTOQUE.ID_UNIDADE);
        public static final ForeignKey<EnReceitaRecord, EnDificuldadeRecord> EN_RECEITA__EN_RECEITA_EN_DIFICULDADE_ID_DIFICULDADE_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_DIFICULDADE_PKEY, EnReceita.EN_RECEITA, "en_receita__en_receita_en_dificuldade_id_dificuldade_fk", EnReceita.EN_RECEITA.ID_DIFICULDADE);
        public static final ForeignKey<ReIngredienteReceitaRecord, EnIngredienteRecord> RE_INGREDIENTE_RECEITA__EN_INGREDIENTE_RECEITA_EN_INGREDIENTE_ID_INGREDIENTE_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_INGREDIENTE_PKEY, ReIngredienteReceita.RE_INGREDIENTE_RECEITA, "re_ingrediente_receita__en_ingrediente_receita_en_ingrediente_id_ingrediente_fk", ReIngredienteReceita.RE_INGREDIENTE_RECEITA.ID_INGREDIENTE);
        public static final ForeignKey<ReUnidadeUnidadeRecord, EnUnidadeRecord> RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_UNIDADE_PKEY, ReUnidadeUnidade.RE_UNIDADE_UNIDADE, "re_unidade_unidade__re_unidade_unidade_en_unidade_id_unidade_fk", ReUnidadeUnidade.RE_UNIDADE_UNIDADE.ID_UNIDADE_ORIGEM);
        public static final ForeignKey<ReUnidadeUnidadeRecord, EnUnidadeRecord> RE_UNIDADE_UNIDADE__RE_UNIDADE_UNIDADE_EN_UNIDADE_ID_UNIDADE_DESTINO_FK = createForeignKey(br.ufsc.INE5608.homechef.Keys.EN_UNIDADE_PKEY, ReUnidadeUnidade.RE_UNIDADE_UNIDADE, "re_unidade_unidade__re_unidade_unidade_en_unidade_id_unidade_destino_fk", ReUnidadeUnidade.RE_UNIDADE_UNIDADE.ID_UNIDADE_DESTINO);
    }
}
