/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in homechef
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>homechef.en_dificuldade_id_dificuldade_seq</code>
     */
    public static final Sequence<Integer> EN_DIFICULDADE_ID_DIFICULDADE_SEQ = new SequenceImpl<Integer>("en_dificuldade_id_dificuldade_seq", Homechef.HOMECHEF, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>homechef.en_ingrediente_id_ingrediente_seq</code>
     */
    public static final Sequence<Integer> EN_INGREDIENTE_ID_INGREDIENTE_SEQ = new SequenceImpl<Integer>("en_ingrediente_id_ingrediente_seq", Homechef.HOMECHEF, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>homechef.en_ingrediente_receita_id_ingrediente_receita_seq</code>
     */
    public static final Sequence<Integer> EN_INGREDIENTE_RECEITA_ID_INGREDIENTE_RECEITA_SEQ = new SequenceImpl<Integer>("en_ingrediente_receita_id_ingrediente_receita_seq", Homechef.HOMECHEF, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>homechef.en_item_estoque_id_item_estoque_seq</code>
     */
    public static final Sequence<Integer> EN_ITEM_ESTOQUE_ID_ITEM_ESTOQUE_SEQ = new SequenceImpl<Integer>("en_item_estoque_id_item_estoque_seq", Homechef.HOMECHEF, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>homechef.en_receita_id_receita_seq</code>
     */
    public static final Sequence<Integer> EN_RECEITA_ID_RECEITA_SEQ = new SequenceImpl<Integer>("en_receita_id_receita_seq", Homechef.HOMECHEF, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>homechef.en_unidade_id_unidade_seq</code>
     */
    public static final Sequence<Integer> EN_UNIDADE_ID_UNIDADE_SEQ = new SequenceImpl<Integer>("en_unidade_id_unidade_seq", Homechef.HOMECHEF, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
