/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef;


import br.ufsc.INE5608.homechef.tables.EnDificuldade;
import br.ufsc.INE5608.homechef.tables.EnIngrediente;
import br.ufsc.INE5608.homechef.tables.EnItemEstoque;
import br.ufsc.INE5608.homechef.tables.EnReceita;
import br.ufsc.INE5608.homechef.tables.EnUnidade;
import br.ufsc.INE5608.homechef.tables.ReIngredienteReceita;
import br.ufsc.INE5608.homechef.tables.ReUnidadeUnidade;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in homechef
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>homechef.en_dificuldade</code>.
     */
    public static final EnDificuldade EN_DIFICULDADE = br.ufsc.INE5608.homechef.tables.EnDificuldade.EN_DIFICULDADE;

    /**
     * The table <code>homechef.en_ingrediente</code>.
     */
    public static final EnIngrediente EN_INGREDIENTE = br.ufsc.INE5608.homechef.tables.EnIngrediente.EN_INGREDIENTE;

    /**
     * The table <code>homechef.en_item_estoque</code>.
     */
    public static final EnItemEstoque EN_ITEM_ESTOQUE = br.ufsc.INE5608.homechef.tables.EnItemEstoque.EN_ITEM_ESTOQUE;

    /**
     * The table <code>homechef.en_receita</code>.
     */
    public static final EnReceita EN_RECEITA = br.ufsc.INE5608.homechef.tables.EnReceita.EN_RECEITA;

    /**
     * The table <code>homechef.en_unidade</code>.
     */
    public static final EnUnidade EN_UNIDADE = br.ufsc.INE5608.homechef.tables.EnUnidade.EN_UNIDADE;

    /**
     * The table <code>homechef.re_ingrediente_receita</code>.
     */
    public static final ReIngredienteReceita RE_INGREDIENTE_RECEITA = br.ufsc.INE5608.homechef.tables.ReIngredienteReceita.RE_INGREDIENTE_RECEITA;

    /**
     * The table <code>homechef.re_unidade_unidade</code>.
     */
    public static final ReUnidadeUnidade RE_UNIDADE_UNIDADE = br.ufsc.INE5608.homechef.tables.ReUnidadeUnidade.RE_UNIDADE_UNIDADE;
}
