/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables.records;


import br.ufsc.INE5608.homechef.tables.EnDificuldade;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnDificuldadeRecord extends UpdatableRecordImpl<EnDificuldadeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 334886049;

    /**
     * Setter for <code>homechef.en_dificuldade.id_dificuldade</code>.
     */
    public void setIdDificuldade(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>homechef.en_dificuldade.id_dificuldade</code>.
     */
    public Integer getIdDificuldade() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>homechef.en_dificuldade.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>homechef.en_dificuldade.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EnDificuldade.EN_DIFICULDADE.ID_DIFICULDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EnDificuldade.EN_DIFICULDADE.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdDificuldade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnDificuldadeRecord value1(Integer value) {
        setIdDificuldade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnDificuldadeRecord value2(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnDificuldadeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnDificuldadeRecord
     */
    public EnDificuldadeRecord() {
        super(EnDificuldade.EN_DIFICULDADE);
    }

    /**
     * Create a detached, initialised EnDificuldadeRecord
     */
    public EnDificuldadeRecord(Integer idDificuldade, String nome) {
        super(EnDificuldade.EN_DIFICULDADE);

        set(0, idDificuldade);
        set(1, nome);
    }
}
