/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables.records;


import br.ufsc.INE5608.homechef.tables.EnIngrediente;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnIngredienteRecord extends UpdatableRecordImpl<EnIngredienteRecord> implements Record4<Integer, String, BigDecimal, Integer> {

    private static final long serialVersionUID = 812069833;

    /**
     * Setter for <code>homechef.en_ingrediente.id_ingrediente</code>.
     */
    public void setIdIngrediente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>homechef.en_ingrediente.id_ingrediente</code>.
     */
    public Integer getIdIngrediente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>homechef.en_ingrediente.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>homechef.en_ingrediente.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>homechef.en_ingrediente.preco</code>.
     */
    public void setPreco(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>homechef.en_ingrediente.preco</code>.
     */
    public BigDecimal getPreco() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>homechef.en_ingrediente.id_unidade</code>.
     */
    public void setIdUnidade(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>homechef.en_ingrediente.id_unidade</code>.
     */
    public Integer getIdUnidade() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, BigDecimal, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, BigDecimal, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EnIngrediente.EN_INGREDIENTE.ID_INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EnIngrediente.EN_INGREDIENTE.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return EnIngrediente.EN_INGREDIENTE.PRECO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return EnIngrediente.EN_INGREDIENTE.ID_UNIDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdIngrediente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getPreco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdUnidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnIngredienteRecord value1(Integer value) {
        setIdIngrediente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnIngredienteRecord value2(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnIngredienteRecord value3(BigDecimal value) {
        setPreco(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnIngredienteRecord value4(Integer value) {
        setIdUnidade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnIngredienteRecord values(Integer value1, String value2, BigDecimal value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnIngredienteRecord
     */
    public EnIngredienteRecord() {
        super(EnIngrediente.EN_INGREDIENTE);
    }

    /**
     * Create a detached, initialised EnIngredienteRecord
     */
    public EnIngredienteRecord(Integer idIngrediente, String nome, BigDecimal preco, Integer idUnidade) {
        super(EnIngrediente.EN_INGREDIENTE);

        set(0, idIngrediente);
        set(1, nome);
        set(2, preco);
        set(3, idUnidade);
    }
}
