/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables.records;


import br.ufsc.INE5608.homechef.tables.EnItemEstoque;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnItemEstoqueRecord extends UpdatableRecordImpl<EnItemEstoqueRecord> implements Record5<Integer, LocalDate, Integer, Integer, Integer> {

    private static final long serialVersionUID = -808617555;

    /**
     * Setter for <code>homechef.en_item_estoque.quantidade</code>.
     */
    public void setQuantidade(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>homechef.en_item_estoque.quantidade</code>.
     */
    public Integer getQuantidade() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>homechef.en_item_estoque.validade</code>.
     */
    public void setValidade(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>homechef.en_item_estoque.validade</code>.
     */
    public LocalDate getValidade() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>homechef.en_item_estoque.id_ingrediente</code>.
     */
    public void setIdIngrediente(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>homechef.en_item_estoque.id_ingrediente</code>.
     */
    public Integer getIdIngrediente() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>homechef.en_item_estoque.id_item_estoque</code>.
     */
    public void setIdItemEstoque(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>homechef.en_item_estoque.id_item_estoque</code>.
     */
    public Integer getIdItemEstoque() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>homechef.en_item_estoque.id_unidade</code>.
     */
    public void setIdUnidade(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>homechef.en_item_estoque.id_unidade</code>.
     */
    public Integer getIdUnidade() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, LocalDate, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, LocalDate, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EnItemEstoque.EN_ITEM_ESTOQUE.QUANTIDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field2() {
        return EnItemEstoque.EN_ITEM_ESTOQUE.VALIDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EnItemEstoque.EN_ITEM_ESTOQUE.ID_INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return EnItemEstoque.EN_ITEM_ESTOQUE.ID_ITEM_ESTOQUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return EnItemEstoque.EN_ITEM_ESTOQUE.ID_UNIDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getQuantidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value2() {
        return getValidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdIngrediente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdItemEstoque();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdUnidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnItemEstoqueRecord value1(Integer value) {
        setQuantidade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnItemEstoqueRecord value2(LocalDate value) {
        setValidade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnItemEstoqueRecord value3(Integer value) {
        setIdIngrediente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnItemEstoqueRecord value4(Integer value) {
        setIdItemEstoque(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnItemEstoqueRecord value5(Integer value) {
        setIdUnidade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnItemEstoqueRecord values(Integer value1, LocalDate value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnItemEstoqueRecord
     */
    public EnItemEstoqueRecord() {
        super(EnItemEstoque.EN_ITEM_ESTOQUE);
    }

    /**
     * Create a detached, initialised EnItemEstoqueRecord
     */
    public EnItemEstoqueRecord(Integer quantidade, LocalDate validade, Integer idIngrediente, Integer idItemEstoque, Integer idUnidade) {
        super(EnItemEstoque.EN_ITEM_ESTOQUE);

        set(0, quantidade);
        set(1, validade);
        set(2, idIngrediente);
        set(3, idItemEstoque);
        set(4, idUnidade);
    }
}
