/*
 * This file is generated by jOOQ.
*/
package br.ufsc.INE5608.homechef.tables.records;


import br.ufsc.INE5608.homechef.tables.ReUnidadeUnidade;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReUnidadeUnidadeRecord extends UpdatableRecordImpl<ReUnidadeUnidadeRecord> implements Record3<Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = -151617547;

    /**
     * Setter for <code>homechef.re_unidade_unidade.id_unidade_origem</code>.
     */
    public void setIdUnidadeOrigem(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>homechef.re_unidade_unidade.id_unidade_origem</code>.
     */
    public Integer getIdUnidadeOrigem() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>homechef.re_unidade_unidade.id_unidade_destino</code>.
     */
    public void setIdUnidadeDestino(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>homechef.re_unidade_unidade.id_unidade_destino</code>.
     */
    public Integer getIdUnidadeDestino() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>homechef.re_unidade_unidade.multiplicador</code>.
     */
    public void setMultiplicador(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>homechef.re_unidade_unidade.multiplicador</code>.
     */
    public BigDecimal getMultiplicador() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ReUnidadeUnidade.RE_UNIDADE_UNIDADE.ID_UNIDADE_ORIGEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ReUnidadeUnidade.RE_UNIDADE_UNIDADE.ID_UNIDADE_DESTINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return ReUnidadeUnidade.RE_UNIDADE_UNIDADE.MULTIPLICADOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdUnidadeOrigem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdUnidadeDestino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getMultiplicador();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReUnidadeUnidadeRecord value1(Integer value) {
        setIdUnidadeOrigem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReUnidadeUnidadeRecord value2(Integer value) {
        setIdUnidadeDestino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReUnidadeUnidadeRecord value3(BigDecimal value) {
        setMultiplicador(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReUnidadeUnidadeRecord values(Integer value1, Integer value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReUnidadeUnidadeRecord
     */
    public ReUnidadeUnidadeRecord() {
        super(ReUnidadeUnidade.RE_UNIDADE_UNIDADE);
    }

    /**
     * Create a detached, initialised ReUnidadeUnidadeRecord
     */
    public ReUnidadeUnidadeRecord(Integer idUnidadeOrigem, Integer idUnidadeDestino, BigDecimal multiplicador) {
        super(ReUnidadeUnidade.RE_UNIDADE_UNIDADE);

        set(0, idUnidadeOrigem);
        set(1, idUnidadeDestino);
        set(2, multiplicador);
    }
}
