/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.main.java.br.ufsc.INE5608.homechef.view;

import src.main.java.br.ufsc.INE5608.homechef.controller.ControladorIngrediente;
import src.main.java.br.ufsc.INE5608.homechef.dto.IngredienteDTO;

import javax.swing.*;
import java.util.Collection;

/**
 *
 * @author Gabriel
 */
public class FmListarIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FmListarIngredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ingredienteTable = new javax.swing.JTable();
        ingredienteLabel = new javax.swing.JLabel();
        incluiBtn = new javax.swing.JButton();
        alteraBtn = new javax.swing.JButton();
        excluiBtn = new javax.swing.JButton();
        fecharBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ingredienteTable.setModel(new IngredienteTableModel());
        jScrollPane1.setViewportView(ingredienteTable);
        if (ingredienteTable.getColumnModel().getColumnCount() > 0) {
            ingredienteTable.getColumnModel().getColumn(2).setResizable(false);
        }

        ingredienteLabel.setText("Ingredientes:");

        incluiBtn.setText("Inclui");
        incluiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluiBtnActionPerformed(evt);
            }
        });

        alteraBtn.setText("Altera");
        alteraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraBtnActionPerformed(evt);
            }
        });

        excluiBtn.setText("Exclui");
        excluiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiBtnActionPerformed(evt);
            }
        });

        fecharBtn.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fecharBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ingredienteLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alteraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(incluiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingredienteLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(incluiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alteraBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluiBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(fecharBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void incluiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluiBtnActionPerformed
        ControladorIngrediente.getInstance().abreInclusao();
    }//GEN-LAST:event_incluiBtnActionPerformed

    private void excluiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiBtnActionPerformed
        IngredienteTableModel model = (IngredienteTableModel) ingredienteTable.getModel();
        int selectedRow = ingredienteTable.getSelectedRow();
        if (selectedRow > -1) {
            IngredienteDTO selecionado = model.getValueAt(selectedRow);
            try {
                ControladorIngrediente.getInstance().exclui(selecionado);
                JOptionPane.showMessageDialog(null, "Ingrediente removido!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_excluiBtnActionPerformed

    private void alteraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraBtnActionPerformed
        IngredienteTableModel model = (IngredienteTableModel) ingredienteTable.getModel();
        IngredienteDTO selecionado = model.getValueAt(ingredienteTable.getSelectedRow());
        ControladorIngrediente.getInstance().abreAlteracao(selecionado);
    }//GEN-LAST:event_alteraBtnActionPerformed

    public void setaIntegredientesTable(Collection<IngredienteDTO> ingredientes) {
        removeLinhas();
        IngredienteTableModel model = (IngredienteTableModel) ingredienteTable.getModel();
        ingredientes.forEach(
                model::addIngredienteDTO
        );
    }

    private void removeLinhas() {
        IngredienteTableModel model = (IngredienteTableModel) ingredienteTable.getModel();
        int linhas = model.getRowCount();
        for (int i = linhas - 1; i >= 0; i--) {
            model.removeIngredienteDTO(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alteraBtn;
    private javax.swing.JButton excluiBtn;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JButton incluiBtn;
    private javax.swing.JLabel ingredienteLabel;
    private javax.swing.JTable ingredienteTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
